# inherit_from: rubocop-todo.yml

AllCops:
  Exclude:
    - '_old/**/*'

FileName:
  Exclude:
    - Guardfile

LineLength:
  Max: 99

AlignHash:
  EnforcedColonStyle: table

AccessModifierIndentation:
  EnforcedStyle: outdent

MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

SpaceInsideBlockBraces:
  Enabled: false
  # EnforcedStyle: no_space
  # SupportedStyles:
  #   - space
  #   - no_space
  # # Valid values are: space, no_space
  # EnforcedStyleForEmptyBraces: no_space
  # # Space between { and |. Overrides EnforcedStyle if there is a conflict.
  # SpaceBeforeBlockParameters: false

DotPosition:
  EnforcedStyle: trailing

StringLiterals:
  EnforcedStyle: single_quotes

SignalException:
  EnforcedStyle: semantic

HashSyntax:
  EnforcedStyle: ruby19

Documentation:
  Enabled: false

RegexpLiteral:
  Enabled: false