# inherit_from: rubocop-todo.yml

AllCops:
  Exclude:
    - '_old/**'

FileName:
  Exclude:
    - Guardfile

LineLength:
  Max: 99

AccessModifierIndentation:
  EnforcedStyle: outdent

MethodDefParentheses:
  EnforcedStyle: require_parentheses

SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SupportedStyles:
    - space
    - no_space
  # Valid values are: space, no_space
  EnforcedStyleForEmptyBraces: no_space
  # Space between { and |. Overrides EnforcedStyle if there is a conflict.
  SpaceBeforeBlockParameters: false
